### ISSUE TITLE
How to use modifyVars

### ISSUE THREAD

**Issue by blaugueux** [plus3network/gulp-less#50] opened 2014-05-12 06:47 UTC
Hi everyone,

I really don't understand how to use modifyVars with ```gulp-less```. I can't find any docs about this.

Here is my code : 
```
// ...
.pipe(less({modifyVars: {myVar: 1}});
// ...
```
I ran this error : 
```Error in plugin 'gulp-less': variable @myVar is undefined in file...```

Thanks for your help

**Comment by contra** [comment] 2015-02-11 20:50
Duplicate of #67

**Closed by contra** 2015-02-11 20:50 UTC
