### ISSUE TITLE
Sourcemaps + no output = failing less parser 

### ISSUE THREAD

**Issue by johngeorgewright** [plus3network/gulp-less#146] opened 2015-02-16 09:48 UTC
I'm unsure where this problem stems from, but if I have a LESS file that doesn't result in any CSS output, then try compiling it using this gulp plugin, with sourcemaps, the LESS parser starts complaining about unexpected output `u`. E.g:

```js
// gulp task
gulp.task('css:dev', function () {
  return gulp
    .src(SOURCE_FILES)
    .pipe(sourcemaps.init())
    .pipe(less())
    .on('error', console.error)
    .pipe(concat('main.css'))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(BUILD_DIR));
});
```

```less
some-tag {
  // This will result in an empty output file
}
```

```
 $ gulp css:dev
[09:37:35] Using gulpfile gulpfile.js
[09:37:35] Starting 'css:dev'...

node_modules/gulp-less/node_modules/less/lib/less/parser/parser.js:183
                    return callback(null, root);
                           ^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at node_modules/gulp-less/node_modules/accord/lib/adapters/less.js:48:32
    at node_modules/gulp-less/node_modules/less/lib/less/parse.js:63:17
    at Object.finish [as _finish] (node_modules/gulp-less/node_modules/less/lib/less/parser/parser.js:183:28)
    at Object.ImportVisitor._onSequencerEmpty (/node_modules/gulp-less/node_modules/less/lib/less/visitors/import-visitor.js:35:14)
    at ImportSequencer.tryRun (node_modules/gulp-less/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)
    at Object.ImportVisitor.run (node_modules/gulp-less/node_modules/less/lib/less/visitors/import-visitor.js:29:25)
    at Object.Parser.parse (node_modules/gulp-less/node_modules/less/lib/less/parser/parser.js:189:22)
    at Object.parse (node_modules/gulp-less/node_modules/less/lib/less/parse.js:61:18)
```

Every will start working when taking away the sourcemap integration.

**Comment by contra** [comment] 2015-02-16 11:12
Duplicate of https://github.com/plus3network/gulp-less/issues/122

**Closed by contra** 2015-02-16 11:12 UTC
