### ISSUE TITLE
Less task always outputs an empty CSS file

### ISSUE THREAD

**Issue by arm1n** [plus3network/gulp-less#103] opened 2014-11-12 10:28 UTC
Hi there!

As I'm using less for my project I wanted to use gulp-less for compilation purposes. After trying to compile my project files without any success, I thought I should test it with example setup located in your repo's `examples` directory - but even compiling this simple less file results in an empty css file without any error/stack trace. Even logging results from `less.render` shows that compilation works, but I've no clue why the files are empty. Compared to other plugins used in my setup such as `cssmin` or `uglify` I cannot get any explanation for this, as they all work in a similar way and use same plugins (f.e. `trough2`). 

Here's my setup:

```js
// gulpfile.js:
gulp.task('compile',function(){
	return gulp
		.src(assetsPath+'/test.less')
		.pipe(less())
		.pipe(gulp.dest(assetsPath));
});

// test.less
@color-base: #2d5e8b;
 
.class1 {
    background-color: @color-base;
}
.class2 {
    background-color: #fff;
    color: @color-base;
}
.class3 {
    border: 1px solid @color-base;
}
```

My current/updated versions:

- node: `0.10.33`
- gulp: `3.8.10`
- gulp-less: `1.3.6`

Any help would be greatly appreciated - thank you!

**Comment by areichman** [comment] 2015-01-22 14:41
Using the same basic gulpfile as @hrach above. On a Windows dev box with gulp 3.8.10 and gulp-less 2.0.1, I don't get any files written at all, let alone a blank CSS file. The `.pipe(less())` part just seems to die without passing anything through from `gulp.src`.  If I comment out the `.pipe(less())` line the original .less file is written to the build directory as expected.

Further, with the less command still active, I only see "Starting less" in the gulp output.  It never displays the "Finished less..." line.

**Comment by contra** [comment] 2015-01-22 22:33
@areichman Seems like this is probably a duplicate of https://github.com/plus3network/gulp-less/issues/118 check your less for errors

**Comment by hrach** [comment] 2015-01-22 23:07
My issue was thet it didn't wotk with less >= 2.0.0. Adding constraint to less < 2.0.0 helped.

**Comment by contra** [comment] 2015-02-11 19:12
Okay, closing this since it was a less version issue

**Closed by contra** 2015-02-11 19:12 UTC

**Comment by jorguema** [comment] 2015-06-23 14:02
Its a bit confusing, i have 2
