### ISSUE TITLE
Error throw when save 

### ISSUE THREAD

**Issue by DavidStrada** [plus3network/gulp-less#182] opened 2015-08-13 01:51 UTC
I keep having the same error after saving a file ( removed comments `// or /*  .... */` I was using the latest version `3.0.3` installed via npm, if i downgrade the version to `1.3.9` it works, here is my log.

`/Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/decorators/unhandledRejection.js:80
		throw e;
		      ^
TypeError: Cannot read property 'rules' of undefined
    at Import.eval (/Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/tree/import.js:140:46)
    at Ruleset.evalImports (/Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/tree/ruleset.js:188:36)
    at Ruleset.eval (/Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/tree/ruleset.js:96:17)
    at module.exports (/Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/transform-tree.js:66:22)
    at ParseTree.toCSS (/Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/parse-tree.js:14:25)
    at /Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/render.js:31:40
    at /Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/parse.js:63:17
    at Object.finish [as _finish] (/Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/parser/parser.js:183:28)`

[ x ] I checked for circular dependencies ( none ).
[ x ] I saw an checked previous bug reports https://github.com/plus3network/gulp-less/issues/114 , https://github.com/less/less.js/issues/2430 reporting the same "bug".

If you need more info do let me know.

Thanks!

**Comment by stevelacy** [comment] 2015-08-13 02:20
Duplicate of #114, https://github.com/less/less.js/issues/2430
Opening new issues on this project won't speed up `less` fixing the issue.

**Closed by stevelacy** 2015-08-13 02:20 UTC
