### ISSUE TITLE
done not defined on promise

### ISSUE THREAD

**Issue by smussell** [plus3network/gulp-less#141] opened 2015-02-11 21:39 UTC
I'm getting the following error after updating to the latest gulp-less version.

```
/node_modules/gulp-less/index.js:69
    }).done(undefined, cb);
       ^
TypeError: Object #<Promise> has no method 'done'
    at DestroyableTransform._transform (/node_modules/reviz-dev/node_modules/gulp-less/index.js:69:8)
    at DestroyableTransform.Transform._read (/node_modules/reviz-dev/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/node_modules/reviz-dev/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/node_modules/reviz-dev/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/node_modules/reviz-dev/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/node_modules/reviz-dev/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:92:17)
```

My node version is 0.10.36

**Comment by contra** [comment] 2015-02-11 22:37
duplicate of #140

**Closed by contra** 2015-02-11 22:37 UTC
