### ISSUE TITLE
using font-awesome in :before

### ISSUE THREAD

**Issue by whisher** [plus3network/gulp-less#179] opened 2015-07-29 15:45 UTC
Hi,
may be a bug with 
```css
&:before {
    &:extend(.fa);
    &:extend(.fa-circle-o-notch);
    &:extend(.fa-spin);
    color:#F0F3F4;
    font-size: 5em;
    position: absolute;
    top: 50%;
  }
```
you should use 

>@import (less) 'font-awesome.css';

afaik
As of LESS >= 1.6 rules with interpolated selectors can be accessed as mixins.

Best regards

**Comment by stevelacy** [comment] 2015-07-29 23:52
Closing as it is not a bug or issue with this project.

**Closed by stevelacy** 2015-07-29 23:52 UTC
