### ISSUE TITLE
Less compilation breaks on files that only contain comments

### ISSUE THREAD

**Issue by dcryan** [plus3network/gulp-less#114] opened 2014-12-05 22:03 UTC
This wasn't an issue with 1.3.6

Breaks when trying to compile files that only contain comments both single line and multi-line

Example 1:
```
// breaks on single line comments
```

Example 2:
```
/*
breaks also on multi-line comments
with a following commented less example
div{
background: transparent;
}
*/
```

**Comment by contra** [comment] 2015-02-11 19:12
This is a duplicate of https://github.com/less/less.js/issues/2430

**Closed by contra** 2015-02-11 19:12 UTC
