### ISSUE TITLE
SVG Gradients compile incorrectly

### ISSUE THREAD

**Issue by digitaldreamd** [plus3network/gulp-less#147] opened 2015-02-16 21:32 UTC
From the reference: http://lesscss.org/functions/#misc-functions-svg-gradient
```
background-image: svg-gradient(to right, red, green 30%, blue);
```
Should compile to:
```
background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB2ZXJzaW9uPSIxLjEiIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIHZpZXdCb3g9IjAgMCAxIDEiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxsaW5lYXJHcmFkaWVudCBpZD0iZ3JhZGllbnQiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIiB4MT0iMCUiIHkxPSIwJSIgeDI9IjEwMCUiIHkyPSIwJSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2ZmMDAwMCIvPjxzdG9wIG9mZnNldD0iMzAlIiBzdG9wLWNvbG9yPSIjMDA4MDAwIi8+PHN0b3Agb2Zmc2V0PSIxMDAlIiBzdG9wLWNvbG9yPSIjMDAwMGZmIi8+PC9saW5lYXJHcmFkaWVudD48cmVjdCB4PSIwIiB5PSIwIiB3aWR0aD0iMSIgaGVpZ2h0PSIxIiBmaWxsPSJ1cmwoI2dyYWRpZW50KSIgLz48L3N2Zz4=')
```
Instead, I end up with this:
```
background-image: url("'data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20%3F%3E%3Csvg%20xmlns…D%220%22%20width%3D%221%22%20height%3D%221%22%20fill%3D%22url(%23gradient")%22%20%2F%3E%3C%2Fsvg%3E');
```
Any idea what could be causing this?

**Comment by stevelacy** [comment] 2015-02-16 22:00
Please compile the code on the less CLI.
Add:
- gulp-less version
- gulp version
- less version

**Comment by digitaldreamd** [comment] 2015-02-16 22:09
gulp-less@2.0.3
gulp@3.8.11
lessc 2.4.0 (Less Compiler) [JavaScript]

Compiling using lessc direct does give the same result. I realise that this means that the issue isn't with gulp-less, however do you have any ideas on possible fixes?

**Comment by stevelacy** [comment] 2015-02-16 22:15
Open an issue on less, the error looks like an incorrect escape of the svg output.

BTW: update `gulp-less` to 3.0.0

**Comment by stevelacy** [comment] 2015-02-17 18:32
I will close this as we have confirmed that the issue is on `lessc`.
Re-open if it has relations to `gulp-less`

**Closed by stevelacy** 2015-02-17 18:32 UTC
