### ISSUE TITLE
Less compilation doesn't break on missing variable

### ISSUE THREAD

**Issue by mike-engel** [plus3network/gulp-less#118] opened 2014-12-17 18:16 UTC
Not sure if this issue should be here or in the less repo, but here it is. I recently did a lot of refactoring and after deleting a certain file, the less task would never finish, which would cause more problems in the default task as you can imagine. After going through all the changes, I found that I had deleted a variable that was used in another file. Even though less should have thrown an error about a missing variable, it didn't.

I'm not sure if I've missed something with less 2.0.0 or if this is a bug between one or both repos.

Thanks!

**Comment by magicdawn** [comment] 2015-01-11 14:12
I don't understand what's doing in the index.js

```js
cb(error)
```
since we can't see the error. why not just use `gutil.log` tell us what's wrong...

**Comment by magicdawn** [comment] 2015-01-11 14:14
here is the  problem :  plugin catch error & pass to the callback & no error show on console

**Comment by contra** [comment] 2015-01-12 09:41
I have a test case that is reproducing this but I have no idea why the error isn't ending the stream

**Comment by contra** [comment] 2015-02-11 19:11
fixed in 2.0.3

**Closed by contra** 2015-02-11 19:11 UTC
Labels: bug

**Comment by austinpray** [comment] 2015-02-11 19:15
@retlehs

**Comment by mike-engel** [comment] 2015-02-11 19:47
Many thanks @contra and @OhJeez.

**Comment by umefarooq** [comment] 2015-02-11 20:13
thanks for fixing
